### ISSUE TITLE
Hash individual assets

### ISSUE THREAD

**Issue by bayleedev** [mdx-dev/li3_frontender#8]
Currently on production when you include a manifest (`<?= $this->assets->script('global') ?>`) you get a hash like `compiled/global_035e34ab.js` but when including individual assets (`<?=$this->html->script(array('/js/libs/review.js')); ?>`) you don't get the unique hash on the file like `/js/libs/review.js`, which causes caching issues on s3.

**Comment by elijahsummers** [comment]
So I think either:
- there should be a `review` manifest, or
- frontender should allow including individual assets rather than just manifests.

If we allow including individual assets then we can't guarantee that the console asset build we do during deploy will catch all used assets. In practice that probably isn't a huge deal and we'd just see a small performance hit after deploys (unless something weird happens like a flood of requests for an asset triggers multiple compilation/minification runs and the server dies).

**Comment by bayleedev** [comment]
I'll use the quick solution and use a manifest, I do think it would be nice to just ask frontender where `/libs/foo/bar.coffee` is located and it either compile or tell you. We could avoid cache stampedes by pre-compiling individual assets?

I think rails will pre-compile all assets unless the first character of the name is a `_`, which we would just do for most of ours. Thoughts?

**Comment by elijahsummers** [comment]
Aye, it does expose a method for generating the cached name for manifests and assets. Even compiling assets on the fly shouldn't be too tricky.

Maybe an added option on the console command could scan for all available assets and compile them. Sounds very useful to me--it feels a bit silly creating manifests that include only a single asset.
